@api=http://127.0.0.1:9090

### Create login token
POST {{api}}/api/auth
Content-Type: application/json

{
    "email": "example1@email.com"
}

### Login with email and token
POST {{api}}/api/auth
Content-Type: application/json

{
    "email": "example1@email.com",
    "token": "6A5F"
}

### Login with hash
POST {{api}}/api/auth/a2b7a9eac4a3261379bbc83f144368176fa2ce1e13300001d4647025b947847c2e8e7c873305d113ce535e7c2b632570

###
GET {{api}}/api/auth

###
DELETE {{api}}/api/auth

###
GET {{api}}/user