@api={{$dotenv api}}/auth

### Create login token
POST {{api}}/login
Content-Type: application/json

{
    "email": "example1@email.com"
}

### Login with email and token
POST {{api}}/login/token
Content-Type: application/json

{
    "email": "example1@email.com",
    "token": "C80C"
}

### Login with hash
GET {{api}}/login/f5e9d74eb4da2ce056bf17aa8f3f53c00da868b0b63032cb3925bf2f8b67f5bf1338cce97dd1e4b3491c20cb0dc23682

###
GET {{api}}

###
GET {{api}}/logout
