# @api = https://secure.payu.com
@api = https://secure.snd.payu.com
@test = {{$dotenv test}}
@pos_id = {{$dotenv pos_id}}
@MD5 = {{$dotenv MD5}}
@client_id = {{$dotenv client_id}}
@client_secret = {{$dotenv client_secret}}
@shopId = {{$dotenv shopId}}
@token = 1898047f-b8af-47e0-9191-0071b24e1cf8

### Create OAuth Token
POST {{api}}/pl/standard/user/oauth/authorize
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}

### Create an Order
POST {{api}}/api/v2_1/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "notifyUrl": "{{test}}/transaction/notify",
    "continueUrl": "{{test}}/transaction/status",
    "customerIp": "127.0.0.1",
    "merchantPosId": "{{pos_id}}",
    "description": "RTV market",
    "currencyCode": "PLN",
    "totalAmount": "122000",
    "buyer": {
        "email": "john.doe@example.com",
        "phone": "654111654",
        "firstName": "John",
        "lastName": "Doe",
        "language": "pl"
    },
    "products": [
       {
          "name": "Laptop",
          "unitPrice": "100000",
          "quantity": "1"
        },
       {
          "name": "Wireless Mouse for Laptop",
          "unitPrice": "22000",
          "quantity": "1"
        }
    ]
}

### Retrieve an Order
# @prompt orderId
GET {{api}}/api/v2_1/orders/{{orderId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Retrieve Shop Data
GET {{api}}/api/v2_1/shops/{{shopId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Create a Payout
POST {{api}}/api/v2_1/payouts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shopId": "{{shopId}}"
}

### Retrieve a Payout
# @prompt payoutId
GET {{api}}/api/v2_1/payouts/{{payoutId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Retrieve Reference Rates
{{api}}/api/v2_1/fx-providers/ecb/fx-rates
Content-Type: application/json
Authorization: Bearer {{token}}
