@api={{$dotenv api}}/products

###
GET {{api}}

###
GET {{api}}/category/home

###
GET {{api}}/laptops

###
GET {{api}}/laptops/lenovo/lenovo-thinkpad-x1/black/1

###
GET {{api}}/laptops/lenovo/zxc/black/1
